default: &default
  adapter: postgis
  pool: 5
  timeout: 5000
  username: postgres
  password: <%= ENV['PGPASSWORD'] %>
  host: db
test:
  <<: *default
  database: dockerized-rails_test
development:
  <<: *default
  database: dockerized-rails_development
production:
  <<: *default
  database: dockerized-rails_production
