version: '2'
services:
  nginx:
    image: nginx
    volumes:
      - ./containers/production/nginx.conf:/etc/nginx/conf.d/default.conf
    volumes_from:
      - app
    depends_on:
      - app
    ports:
      - 80:80
  db:
    image: mdillon/postgis:latest
    ports:
      - 5432:5432
    env_file:
      - containers/production/.env
  app:
    build:
      context: .
      dockerfile: containers/production/Dockerfile
    env_file:
      - containers/production/.env
    command: containers/scripts/wait-for-it.sh db:5432 -- containers/production/entrypoint
    volumes:
      - assets:/usr/app/dockerized-rails/public/assets
    depends_on:
      - db
    ports:
      - 3000:3000

volumes:
  assets:
